import { useMemo, useState, useEffect, useRef } from "react";
import Modal from "../modal";
import { useMutation, useQuery } from "@apollo/client/react";
import { SIGN_UP_CORPORATE, VALIDATE_COUPON_CODE } from "../../graphql/mutations";
import { GET_PLANS } from "../../graphql/queries";

export function AddCompanyModal({
    open,
    onClose,
}: {
    open: boolean;
    onClose: () => void;
}) {
    const formStorageKey = "addCompanyFormState";
    const isRestoringRef = useRef(false);
    const [companyName, setCompanyName] = useState("");
    const [ownerFirstName, setOwnerFirstName] = useState("");
    const [ownerLastName, setOwnerLastName] = useState("");
    const [email, setEmail] = useState("");
    const [phoneCountryCode, setPhoneCountryCode] = useState("+1");
    const [showCountryDropdown, setShowCountryDropdown] = useState(false);
    const [countrySearch, setCountrySearch] = useState("");
    const [phoneNumber, setPhoneNumber] = useState("");
    
    // Common country codes
    const countryCodes = [
        { code: "+1", country: "United States / Canada", flag: "🇺🇸" },
        { code: "+44", country: "United Kingdom", flag: "🇬🇧" },
        { code: "+61", country: "Australia", flag: "🇦🇺" },
        { code: "+49", country: "Germany", flag: "🇩🇪" },
        { code: "+33", country: "France", flag: "🇫🇷" },
        { code: "+39", country: "Italy", flag: "🇮🇹" },
        { code: "+34", country: "Spain", flag: "🇪🇸" },
        { code: "+31", country: "Netherlands", flag: "🇳🇱" },
        { code: "+32", country: "Belgium", flag: "🇧🇪" },
        { code: "+41", country: "Switzerland", flag: "🇨🇭" },
        { code: "+46", country: "Sweden", flag: "🇸🇪" },
        { code: "+47", country: "Norway", flag: "🇳🇴" },
        { code: "+45", country: "Denmark", flag: "🇩🇰" },
        { code: "+358", country: "Finland", flag: "🇫🇮" },
        { code: "+353", country: "Ireland", flag: "🇮🇪" },
        { code: "+351", country: "Portugal", flag: "🇵🇹" },
        { code: "+48", country: "Poland", flag: "🇵🇱" },
        { code: "+420", country: "Czech Republic", flag: "🇨🇿" },
        { code: "+30", country: "Greece", flag: "🇬🇷" },
        { code: "+36", country: "Hungary", flag: "🇭🇺" },
        { code: "+40", country: "Romania", flag: "🇷🇴" },
        { code: "+359", country: "Bulgaria", flag: "🇧🇬" },
        { code: "+385", country: "Croatia", flag: "🇭🇷" },
        { code: "+421", country: "Slovakia", flag: "🇸🇰" },
        { code: "+386", country: "Slovenia", flag: "🇸🇮" },
        { code: "+372", country: "Estonia", flag: "🇪🇪" },
        { code: "+371", country: "Latvia", flag: "🇱🇻" },
        { code: "+370", country: "Lithuania", flag: "🇱🇹" },
        { code: "+356", country: "Malta", flag: "🇲🇹" },
        { code: "+352", country: "Luxembourg", flag: "🇱🇺" },
        { code: "+357", country: "Cyprus", flag: "🇨🇾" },
        { code: "+81", country: "Japan", flag: "🇯🇵" },
        { code: "+82", country: "South Korea", flag: "🇰🇷" },
        { code: "+86", country: "China", flag: "🇨🇳" },
        { code: "+91", country: "India", flag: "🇮🇳" },
        { code: "+65", country: "Singapore", flag: "🇸🇬" },
        { code: "+852", country: "Hong Kong", flag: "🇭🇰" },
        { code: "+971", country: "UAE", flag: "🇦🇪" },
        { code: "+972", country: "Israel", flag: "🇮🇱" },
        { code: "+27", country: "South Africa", flag: "🇿🇦" },
        { code: "+55", country: "Brazil", flag: "🇧🇷" },
        { code: "+52", country: "Mexico", flag: "🇲🇽" },
        { code: "+54", country: "Argentina", flag: "🇦🇷" },
    ];
    
    // Format phone number for US/Canada (+1)
    const formatPhoneNumber = (value: string): string => {
        // Remove all non-digits
        const digits = value.replace(/\D/g, '');
        
        // Format based on length
        if (digits.length <= 3) {
            return digits;
        } else if (digits.length <= 6) {
            return `(${digits.slice(0, 3)}) ${digits.slice(3)}`;
        } else {
            return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6, 10)}`;
        }
    };
    const [selectedPlan, setSelectedPlan] = useState("");
    const [couponCode, setCouponCode] = useState("");
    const [autoGeneratedCoupon, setAutoGeneratedCoupon] = useState<string>("");
    const [couponValid, setCouponValid] = useState<boolean | null>(null);
    const [couponDiscount, setCouponDiscount] = useState<string>("");
    const [couponError, setCouponError] = useState<string>("");

    const filteredCountryCodes = useMemo(() => {
        const q = countrySearch.trim().toLowerCase();
        if (!q) return countryCodes;
        return countryCodes.filter(
            (cc) =>
                cc.country.toLowerCase().includes(q) ||
                cc.code.toLowerCase().includes(q)
        );
    }, [countrySearch]);
    const [isValidatingCoupon, setIsValidatingCoupon] = useState(false);
    const [addr1, setAddr1] = useState("");
    const [addr2, setAddr2] = useState("");
    const [city, setCity] = useState("");
    const [state, setState] = useState("");
    const [zip, setZip] = useState("");
    const [stateSearch, setStateSearch] = useState("");
    const [showStateDropdown, setShowStateDropdown] = useState(false);
    const [showReview, setShowReview] = useState(false);

    // US States with abbreviations
    const usStates = [
        { code: "AL", name: "Alabama" },
        { code: "AK", name: "Alaska" },
        { code: "AZ", name: "Arizona" },
        { code: "AR", name: "Arkansas" },
        { code: "CA", name: "California" },
        { code: "CO", name: "Colorado" },
        { code: "CT", name: "Connecticut" },
        { code: "DE", name: "Delaware" },
        { code: "FL", name: "Florida" },
        { code: "GA", name: "Georgia" },
        { code: "HI", name: "Hawaii" },
        { code: "ID", name: "Idaho" },
        { code: "IL", name: "Illinois" },
        { code: "IN", name: "Indiana" },
        { code: "IA", name: "Iowa" },
        { code: "KS", name: "Kansas" },
        { code: "KY", name: "Kentucky" },
        { code: "LA", name: "Louisiana" },
        { code: "ME", name: "Maine" },
        { code: "MD", name: "Maryland" },
        { code: "MA", name: "Massachusetts" },
        { code: "MI", name: "Michigan" },
        { code: "MN", name: "Minnesota" },
        { code: "MS", name: "Mississippi" },
        { code: "MO", name: "Missouri" },
        { code: "MT", name: "Montana" },
        { code: "NE", name: "Nebraska" },
        { code: "NV", name: "Nevada" },
        { code: "NH", name: "New Hampshire" },
        { code: "NJ", name: "New Jersey" },
        { code: "NM", name: "New Mexico" },
        { code: "NY", name: "New York" },
        { code: "NC", name: "North Carolina" },
        { code: "ND", name: "North Dakota" },
        { code: "OH", name: "Ohio" },
        { code: "OK", name: "Oklahoma" },
        { code: "OR", name: "Oregon" },
        { code: "PA", name: "Pennsylvania" },
        { code: "RI", name: "Rhode Island" },
        { code: "SC", name: "South Carolina" },
        { code: "SD", name: "South Dakota" },
        { code: "TN", name: "Tennessee" },
        { code: "TX", name: "Texas" },
        { code: "UT", name: "Utah" },
        { code: "VT", name: "Vermont" },
        { code: "VA", name: "Virginia" },
        { code: "WA", name: "Washington" },
        { code: "WV", name: "West Virginia" },
        { code: "WI", name: "Wisconsin" },
        { code: "WY", name: "Wyoming" },
        { code: "DC", name: "District of Columbia" },
    ];

    // International options
    const internationalOptions = [
        { code: "AB", name: "Alberta", country: "Canada" },
        { code: "BC", name: "British Columbia", country: "Canada" },
        { code: "MB", name: "Manitoba", country: "Canada" },
        { code: "NB", name: "New Brunswick", country: "Canada" },
        { code: "NL", name: "Newfoundland and Labrador", country: "Canada" },
        { code: "NS", name: "Nova Scotia", country: "Canada" },
        { code: "ON", name: "Ontario", country: "Canada" },
        { code: "PE", name: "Prince Edward Island", country: "Canada" },
        { code: "QC", name: "Quebec", country: "Canada" },
        { code: "SK", name: "Saskatchewan", country: "Canada" },
        { code: "NT", name: "Northwest Territories", country: "Canada" },
        { code: "NU", name: "Nunavut", country: "Canada" },
        { code: "YT", name: "Yukon", country: "Canada" },
    ];

    // Combined options
    const allStateOptions = [
        ...usStates.map(s => ({ ...s, country: "United States" })),
        ...internationalOptions,
        { code: "OTHER", name: "Other (Outside US/Canada)", country: "International" },
    ];

    // Filter states based on search
    const filteredStates = stateSearch.trim()
        ? allStateOptions.filter(
            (s) =>
                s.name.toLowerCase().includes(stateSearch.toLowerCase()) ||
                s.code.toLowerCase().includes(stateSearch.toLowerCase())
        )
        : allStateOptions;

    // Get display text for selected state - now returns only the code
    const getStateDisplay = (stateCode: string) => {
        if (!stateCode) return "";
        const found = allStateOptions.find((s) => s.code === stateCode);
        if (found) {
            return found.code; // Display only the code
        }
        return stateCode;
    };
    
    // Get full name for search/display purposes
    const getStateName = (stateCode: string) => {
        if (!stateCode) return "";
        const found = allStateOptions.find((s) => s.code === stateCode);
        return found ? found.name : stateCode;
    };
    const [errors, setErrors] = useState<Record<string, string>>({});
    const [isSubmitting, setIsSubmitting] = useState(false);
    
    // For backend compatibility - these will be set when a plan is selected
    const [numLicenses, setNumLicenses] = useState("");
    const [stripePriceId, setStripePriceId] = useState("");

    // Fetch corporate plans
    const { data: plansData, loading: plansLoading, error: plansError } = useQuery<{ plans: Array<{ priceId: string; name: string; keys: number; order: number; cents: number; interval: string; currency: string }> }>(GET_PLANS, {
        variables: { memberFlow: "Corporate" },
        skip: !open, // Only fetch when modal is open
        errorPolicy: "all", // Continue even if there are errors
        fetchPolicy: "network-only", // Always fetch fresh data
        notifyOnNetworkStatusChange: true,
    });

    const plans = plansData?.plans || [];
    
    // Generate auto coupon code when modal opens
    useEffect(() => {
        if (open && !autoGeneratedCoupon) {
            // Use a permanent coupon code: FREECORP
            // This is a permanent, reusable coupon code
            const generatedCode = "FREECORP";
            setAutoGeneratedCoupon(generatedCode);
            setCouponCode(generatedCode);
            
            // Auto-validate the generated coupon after a short delay
            const timeoutId = setTimeout(() => {
                handleApplyCoupon(generatedCode);
            }, 500);
            
            return () => clearTimeout(timeoutId);
        }
    }, [open]);

    // Restore saved form state on open
    useEffect(() => {
        if (!open) return;
        const raw = localStorage.getItem(formStorageKey);
        if (!raw) return;
        try {
            const saved = JSON.parse(raw);
            isRestoringRef.current = true;
            setCompanyName(saved.companyName ?? "");
            setOwnerFirstName(saved.ownerFirstName ?? "");
            setOwnerLastName(saved.ownerLastName ?? "");
            setEmail(saved.email ?? "");
            setPhoneCountryCode(saved.phoneCountryCode ?? "+1");
            setPhoneNumber(saved.phoneNumber ?? "");
            setSelectedPlan(saved.selectedPlan ?? "");
            setCouponCode(saved.couponCode ?? "");
            setCouponValid(saved.couponValid ?? null);
            setCouponDiscount(saved.couponDiscount ?? "");
            setCouponError(saved.couponError ?? "");
            setAddr1(saved.addr1 ?? "");
            setAddr2(saved.addr2 ?? "");
            setCity(saved.city ?? "");
            setState(saved.state ?? "");
            setZip(saved.zip ?? "");
            setStateSearch(saved.stateSearch ?? "");
            setShowStateDropdown(false);
            setNumLicenses(saved.numLicenses ?? "");
            setStripePriceId(saved.stripePriceId ?? "");
        } catch (error) {
            console.warn("[ADD_COMPANY] Failed to restore form state:", error);
        } finally {
            isRestoringRef.current = false;
        }
    }, [open]);

    // Keep plan metadata in sync when restoring selected plan
    useEffect(() => {
        if (!open || !selectedPlan || plans.length === 0) return;
        if (stripePriceId && numLicenses) return;
        const plan = plans.find((p: any) => p.priceId === selectedPlan);
        if (plan) {
            if (!stripePriceId) setStripePriceId(plan.priceId || "");
            if (!numLicenses) setNumLicenses((plan.keys || 0).toString());
        }
    }, [open, plans, selectedPlan, stripePriceId, numLicenses]);

    // Persist form state while modal is open
    useEffect(() => {
        if (!open || isRestoringRef.current) return;
        const payload = {
            companyName,
            ownerFirstName,
            ownerLastName,
            email,
            phoneCountryCode,
            phoneNumber,
            selectedPlan,
            couponCode,
            couponValid,
            couponDiscount,
            couponError,
            addr1,
            addr2,
            city,
            state,
            zip,
            stateSearch,
            numLicenses,
            stripePriceId,
        };
        localStorage.setItem(formStorageKey, JSON.stringify(payload));
    }, [
        open,
        companyName,
        ownerFirstName,
        ownerLastName,
        email,
        phoneCountryCode,
        phoneNumber,
        selectedPlan,
        couponCode,
        couponValid,
        couponDiscount,
        couponError,
        addr1,
        addr2,
        city,
        state,
        zip,
        stateSearch,
        numLicenses,
        stripePriceId,
    ]);

    // Enhanced debug logging
    useEffect(() => {
        if (!open) return;
        
        try {
            if (plansLoading) {
                console.log("[ADD_COMPANY] Loading corporate plans...");
            } else if (plansError) {
                console.error("[ADD_COMPANY] Error fetching plans:", plansError);
                if ('graphQLErrors' in plansError) {
                    console.error("[ADD_COMPANY] GraphQL errors:", (plansError as any).graphQLErrors);
                }
                if ('networkError' in plansError) {
                    console.error("[ADD_COMPANY] Network error:", (plansError as any).networkError);
                }
            } else if (plansData && plansData.plans) {
                console.log("[ADD_COMPANY] Plans loaded successfully:");
                console.log("[ADD_COMPANY] Plans data:", plansData);
                console.log("[ADD_COMPANY] Number of plans:", plansData.plans.length);
                if (Array.isArray(plansData.plans)) {
                    plansData.plans.forEach((plan: any, index: number) => {
                        console.log(`[ADD_COMPANY] Plan ${index + 1}:`, {
                            name: plan.name,
                            priceId: plan.priceId,
                            keys: plan.keys,
                            order: plan.order,
                            cents: plan.cents,
                            interval: plan.interval,
                        });
                    });
                }
            }
        } catch (error) {
            console.error("[ADD_COMPANY] Error in useEffect:", error);
        }
    }, [open, plansLoading, plansError, plansData]);

    const [signUpCorporate] = useMutation(SIGN_UP_CORPORATE, {
        errorPolicy: "all",
    });

    const [validateCouponCode] = useMutation(VALIDATE_COUPON_CODE, {
        errorPolicy: "all",
    });

    const handleApplyCoupon = async (codeToValidate?: string) => {
        const code = codeToValidate || couponCode.trim();
        if (!code) {
            setCouponError("Please enter a coupon code");
            setCouponValid(false);
            return;
        }

        setIsValidatingCoupon(true);
        setCouponError("");
        setCouponValid(null);

        try {
            const result = await validateCouponCode({
                variables: { code: code },
            });

            const validation = (result.data as any)?.validateCouponCode;
            if (validation?.valid) {
                setCouponValid(true);
                setCouponDiscount(validation.discount || "");
                setCouponError("");
            } else {
                setCouponValid(false);
                setCouponError(validation?.error || "Invalid coupon code");
                setCouponDiscount("");
            }
        } catch (error: any) {
            setCouponValid(false);
            setCouponError(error.message || "Error validating coupon code");
            setCouponDiscount("");
        } finally {
            setIsValidatingCoupon(false);
        }
    };

    const handleClearCoupon = () => {
        setCouponCode("");
        setCouponValid(null);
        setCouponDiscount("");
        setCouponError("");
        setAutoGeneratedCoupon("");
    };

    const validateForm = (): boolean => {
        const newErrors: Record<string, string> = {};

        if (!companyName.trim()) newErrors.companyName = "Company name is required";
        if (!ownerFirstName.trim()) newErrors.ownerFirstName = "Owner first name is required";
        if (!ownerLastName.trim()) newErrors.ownerLastName = "Owner last name is required";
        if (!email.trim()) {
            newErrors.email = "Email is required";
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
            newErrors.email = "Please enter a valid email address";
        }
        // Validate phone number - check if it has digits (after removing formatting)
        const phoneDigits = phoneNumber.replace(/\D/g, '');
        if (!phoneDigits || phoneDigits.length < 7) {
            newErrors.phoneNumber = "Phone number is required and must be at least 7 digits";
        }
        if (!selectedPlan.trim()) {
            newErrors.selectedPlan = "Default plan is required";
        }
        if (couponCode.trim() && couponValid !== true) {
            newErrors.couponCode = "Please apply a valid coupon code";
            setCouponValid(false);
            setCouponError("Please apply a valid coupon code");
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!validateForm()) {
            return;
        }

        // Show review instead of submitting
        setShowReview(true);
    };

    const handleConfirm = async () => {
        setIsSubmitting(true);

        try {
            // Build address object
            const trimmedAddr1 = addr1.trim();
            const trimmedCity = city.trim();
            const trimmedState = state.trim();
            const trimmedZip = zip.trim();
            const hasAnyAddress = Boolean(trimmedAddr1 || trimmedCity || trimmedState || trimmedZip);
            const hasCompleteAddress = Boolean(trimmedAddr1 && trimmedCity && trimmedState && trimmedZip);

            let address = undefined;
            if (hasAnyAddress) {
                // Only send address if required fields are present
                if (hasCompleteAddress) {
                    address = {
                        addr1: trimmedAddr1,
                        addr2: addr2.trim() || undefined,
                        city: trimmedCity,
                        state: trimmedState,
                        zip: trimmedZip,
                    };
                } else {
                    // If partial address (and not using same-as-billing), show error
                    setErrors({
                        ...errors,
                        address: "Please complete all required address fields (Address Line 1, City, State, ZIP)",
                    });
                    setIsSubmitting(false);
                    return;
                }
            }

            const corporateInput = {
                        companyName: companyName.trim(),
                        firstName: ownerFirstName.trim(),
                        lastName: ownerLastName.trim(),
                        email: email.trim().toLowerCase(),
                phone: `${phoneCountryCode} ${phoneNumber.replace(/\D/g, '')}`.trim(),
                contactConsent: false,
                        numLicenses: Number(numLicenses),
                        priceId: stripePriceId.trim(),
                        address: address,
                couponCode: couponCode.trim() && couponValid ? couponCode.trim() : undefined,
                sameAsBilling: false,
            };
            
            console.log('[FRONTEND] Sending corporate signup data:', {
                hasAddress: !!corporateInput.address,
                address: corporateInput.address,
            });

            // Store payload so we can retry checkout if payment fails
            localStorage.setItem(
                "pendingCorporateSignupPayload",
                JSON.stringify(corporateInput)
            );
            
            const result = await signUpCorporate({
                variables: {
                    corporate: corporateInput,
                },
            });

            const checkoutUrl = (result.data as any)?.signUpCorporate?.checkoutUrl;
            const checkoutSessionId = (result.data as any)?.signUpCorporate?.checkoutSessionId;
            if (checkoutUrl) {
                // Store checkout session ID for manual processing after redirect
                if (checkoutSessionId) {
                    localStorage.setItem('pendingCorporateCheckoutSessionId', checkoutSessionId);
                }
                // Redirect to Stripe checkout
                window.location.href = checkoutUrl;
            } else {
                // If no checkout URL, close modal and show success
                handleClose();
                // You might want to show a success message here
            }
        } catch (error: any) {
            console.error("Error creating company:", error);
            setErrors({
                submit: error.message || "Failed to create company. Please try again.",
            });
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleBackToForm = () => {
        setShowReview(false);
    };

    const handleClose = () => {
        // Reset form
        setCompanyName("");
        setOwnerFirstName("");
        setOwnerLastName("");
        setEmail("");
        setPhoneCountryCode("+1");
        setPhoneNumber("");
        setShowCountryDropdown(false);
        setCountrySearch("");
        setSelectedPlan("");
        setCouponCode("");
        setAutoGeneratedCoupon("");
        setCouponValid(null);
        setCouponDiscount("");
        setCouponError("");
        setAddr1("");
        setAddr2("");
        setCity("");
        setState("");
        setZip("");
        setStateSearch("");
        setShowStateDropdown(false);
        setNumLicenses("");
        setStripePriceId("");
        setShowReview(false);
        setErrors({});
        localStorage.removeItem(formStorageKey);
        onClose();
    };

    return (
        <Modal
            open={open}
            onClose={handleClose}
            title={
                    <div className="flex-1">
                        <div className="text-xl font-semibold">
                            {showReview ? "Review Information" : "Add Company"}
                        </div>
                        <div className="text-sm text-gray-600 mt-1">
                            {showReview 
                                ? "Please review the information below before proceeding to checkout."
                                : "Enter the company details and subscription information below."}
                        </div>
                    </div>
            }
            showCloseButton={false}
            size="md"
        >
            {showReview ? (
                <div className="space-y-6">
                    {/* Review Section */}
                    <div className="bg-gray-50 rounded-lg p-6 space-y-6">
                        {/* Company Information */}
                        <div>
                            <h3 className="text-lg font-semibold text-gray-900 mb-4">Company Information</h3>
                            <div className="space-y-3">
                                <div>
                                    <span className="text-sm font-medium text-gray-600">Company Name:</span>
                                    <p className="text-sm text-gray-900 mt-1">{companyName}</p>
                                </div>
                                <div>
                                    <span className="text-sm font-medium text-gray-600">Owner Name:</span>
                                    <p className="text-sm text-gray-900 mt-1">{ownerFirstName} {ownerLastName}</p>
                                </div>
                                <div>
                                    <span className="text-sm font-medium text-gray-600">Email:</span>
                                    <p className="text-sm text-gray-900 mt-1">{email}</p>
                                </div>
                                <div>
                                    <span className="text-sm font-medium text-gray-600">Phone:</span>
                                    <p className="text-sm text-gray-900 mt-1">{phoneCountryCode} {phoneNumber}</p>
                                </div>
                            </div>
                        </div>

                        {/* Subscription Information */}
                        <div>
                            <h3 className="text-lg font-semibold text-gray-900 mb-4">Subscription Information</h3>
                            <div className="space-y-3">
                                <div>
                                    <span className="text-sm font-medium text-gray-600">Plan:</span>
                                    <p className="text-sm text-gray-900 mt-1">
                                        {(() => {
                                            const plan = plans.find((p: any) => p.priceId === selectedPlan);
                                            if (plan) {
                                                const amount = plan.cents ? `$${(plan.cents / 100).toFixed(2)}` : '';
                                                const interval = plan.interval ? `/${plan.interval}` : '';
                                                return `${plan.name || 'Corporate License'}${amount ? ` (${amount}${interval})` : ''}`;
                                            }
                                            return selectedPlan || 'Not selected';
                                        })()}
                                    </p>
                                </div>
                                {couponCode && couponValid && (
                                    <div>
                                        <span className="text-sm font-medium text-gray-600">Coupon Code:</span>
                                        <p className="text-sm text-green-600 font-medium mt-1">
                                            {couponCode} - {couponDiscount}
                                        </p>
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* Address Information */}
                        {(addr1 || city || state || zip) && (
                            <div>
                                <h3 className="text-lg font-semibold text-gray-900 mb-4">Address Information</h3>
                                <div className="space-y-3">
                                    {addr1 && (
                                        <div>
                                            <span className="text-sm font-medium text-gray-600">Address Line 1:</span>
                                            <p className="text-sm text-gray-900 mt-1">{addr1}</p>
                                        </div>
                                    )}
                                    {addr2 && (
                                        <div>
                                            <span className="text-sm font-medium text-gray-600">Address Line 2:</span>
                                            <p className="text-sm text-gray-900 mt-1">{addr2}</p>
                                        </div>
                                    )}
                                    {(city || state || zip) && (
                                        <div>
                                            <span className="text-sm font-medium text-gray-600">City, State, ZIP:</span>
                                            <p className="text-sm text-gray-900 mt-1">
                                                {[city, state, zip].filter(Boolean).join(", ")}
                                            </p>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Action Buttons */}
                    <div className="flex justify-end gap-3 pt-4">
                        <button
                            type="button"
                            onClick={handleClose}
                            disabled={isSubmitting}
                            className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 bg-white hover:bg-gray-50 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            Clear
                        </button>
                    <button
                        type="button"
                            onClick={handleBackToForm}
                            disabled={isSubmitting}
                            className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 bg-white hover:bg-gray-50 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            Back
                        </button>
                    {errors.submit && (
                        <button
                            type="button"
                            onClick={handleConfirm}
                            disabled={isSubmitting}
                            className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 bg-white hover:bg-gray-50 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            Retry Checkout
                        </button>
                    )}
                        <button
                            type="button"
                            onClick={handleConfirm}
                            disabled={isSubmitting}
                            className="px-6 py-3 text-base text-white rounded-lg transition-colors font-semibold disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                            style={{ backgroundColor: "#064126" }}
                            onMouseEnter={(e) => {
                                if (!e.currentTarget.disabled) {
                                    e.currentTarget.style.backgroundColor = "#052a1a";
                                }
                            }}
                            onMouseLeave={(e) => {
                                if (!e.currentTarget.disabled) {
                                    e.currentTarget.style.backgroundColor = "#064126";
                                }
                            }}
                        >
                            {isSubmitting ? (
                                <>
                        <svg
                                        className="animate-spin h-4 w-4"
                                        xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                                    >
                                        <circle
                                            className="opacity-25"
                                            cx="12"
                                            cy="12"
                                            r="10"
                            stroke="currentColor"
                                            strokeWidth="4"
                                        ></circle>
                                        <path
                                            className="opacity-75"
                                            fill="currentColor"
                                            d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                                        ></path>
                        </svg>
                                    Processing...
                                </>
                            ) : (
                                "Confirm & Proceed to Checkout"
                            )}
                    </button>
                </div>

                    {/* Submit Error */}
                    {errors.submit && (
                        <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
                            <p className="text-sm text-red-600">{errors.submit}</p>
                        </div>
                    )}
                </div>
            ) : (
            <form onSubmit={handleSubmit} className="space-y-6 pb-6">
                {/* Company Name */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1.5">
                        Company Name <span className="text-red-500">*</span>
                    </label>
                    <input
                        type="text"
                        value={companyName}
                        onChange={(e) => setCompanyName(e.target.value)}
                        className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-700 ${
                            errors.companyName
                                ? "border-red-500"
                                : "border-gray-300"
                        }`}
                        placeholder="Acme Corporation"
                    />
                    {errors.companyName && (
                        <p className="mt-1 text-sm text-red-500">{errors.companyName}</p>
                    )}
                </div>

                {/* Owner Information */}
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1.5">
                            Owner First Name <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="text"
                            value={ownerFirstName}
                            onChange={(e) => setOwnerFirstName(e.target.value)}
                            className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-700 ${
                                errors.ownerFirstName
                                    ? "border-red-500"
                                    : "border-gray-300"
                            }`}
                            placeholder="John"
                        />
                        {errors.ownerFirstName && (
                            <p className="mt-1 text-sm text-red-500">{errors.ownerFirstName}</p>
                        )}
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1.5">
                            Owner Last Name <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="text"
                            value={ownerLastName}
                            onChange={(e) => setOwnerLastName(e.target.value)}
                            className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-700 ${
                                errors.ownerLastName
                                    ? "border-red-500"
                                    : "border-gray-300"
                            }`}
                            placeholder="Doe"
                        />
                        {errors.ownerLastName && (
                            <p className="mt-1 text-sm text-red-500">{errors.ownerLastName}</p>
                        )}
                    </div>
                </div>

                {/* Contact Information */}
                <div className="grid grid-cols-2 gap-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1.5">
                            Email <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="email"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-700 ${
                                errors.email ? "border-red-500" : "border-gray-300"
                            }`}
                            placeholder="john@acme.com"
                        />
                        {errors.email && (
                            <p className="mt-1 text-sm text-red-500">{errors.email}</p>
                        )}
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1.5">
                            Phone Number <span className="text-red-500">*</span>
                        </label>
                        <div className="flex gap-2 items-stretch">
                            {/* Country Code Dropdown */}
                            <div className="relative w-28 flex-shrink-0">
                                <button
                                    type="button"
                                    onClick={() => setShowCountryDropdown((open) => !open)}
                                    className="w-full h-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-800 bg-white text-sm text-left flex items-center justify-between"
                                >
                                    <span className="flex items-center gap-2 truncate">
                                        <span>
                                            {countryCodes.find((cc) => cc.code === phoneCountryCode)?.flag || "🌐"}
                                        </span>
                                        <span className="truncate">{phoneCountryCode}</span>
                                    </span>
                                    <span className="text-gray-500">▾</span>
                                </button>
                                {showCountryDropdown && (
                                    <div className="absolute z-50 mt-1 w-full rounded-lg border border-gray-200 bg-white shadow-lg max-h-64 overflow-auto">
                                        <div className="p-2 border-b border-gray-100">
                                            <input
                                                type="text"
                                                value={countrySearch}
                                                onChange={(e) => setCountrySearch(e.target.value)}
                                                placeholder="Search country..."
                                                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-800"
                                            />
                                        </div>
                                        {filteredCountryCodes.map((cc, idx) => (
                                            <button
                                                key={`${cc.country}-${cc.code}-${idx}`}
                                                type="button"
                                                onMouseDown={(e) => {
                                                    e.preventDefault();
                                                    setPhoneCountryCode(cc.code);
                                                    setShowCountryDropdown(false);
                                                    setCountrySearch("");
                                                }}
                                                className="w-full text-left px-3 py-2 hover:bg-gray-50 flex items-center gap-2 text-sm"
                                            >
                                                <span>{cc.flag}</span>
                                                <span className="flex-1 truncate">{cc.country}</span>
                                                <span className="text-gray-600">{cc.code}</span>
                                            </button>
                                        ))}
                                    </div>
                                )}
                            </div>
                            {/* Phone Number Input */}
                            <div className="flex-1">
                        <input
                            type="tel"
                            value={phoneNumber}
                                    onChange={(e) => {
                                        const value = e.target.value;
                                        // Format phone number for US/Canada, otherwise just allow digits
                                        if (phoneCountryCode === "+1") {
                                            // Remove all non-digits first
                                            const digits = value.replace(/\D/g, '');
                                            // Limit to 10 digits for US/Canada
                                            if (digits.length <= 10) {
                                                const formatted = formatPhoneNumber(digits);
                                                setPhoneNumber(formatted);
                                            }
                                        } else {
                                            // For other countries, just allow digits and common separators
                                            const cleaned = value.replace(/[^\d\s\-\(\)\+]/g, '');
                                            setPhoneNumber(cleaned);
                                        }
                                    }}
                                    className={`w-full h-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 ${
                                        errors.phoneNumber ? "border-red-500 focus:ring-red-500" : "border-gray-300 focus:border-gray-700 focus:ring-gray-800"
                            }`}
                                    placeholder={phoneCountryCode === "+1" ? "(555) 123-4567" : "1234567890"}
                                    maxLength={phoneCountryCode === "+1" ? 14 : 20}
                        />
                            </div>
                        </div>
                        {errors.phoneNumber && (
                            <p className="mt-1 text-sm text-red-500">{errors.phoneNumber}</p>
                        )}
                    </div>
                </div>

                {/* Default Plan */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1.5">
                        Default Plan <span className="text-red-500">*</span>
                    </label>
                    <div className="relative">
                        <select
                            value={selectedPlan}
                            onChange={(e) => {
                                const planPriceId = e.target.value;
                                setSelectedPlan(planPriceId);
                                
                                // Find the selected plan and set the related values
                                const plan = plans.find((p: any) => p.priceId === planPriceId);
                                if (plan) {
                                    setStripePriceId(plan.priceId || "");
                                    setNumLicenses((plan.keys || 0).toString());
                                }
                            }}
                            disabled={plansLoading}
                            className={`w-full px-3 py-2 pr-10 border rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-700 appearance-none bg-white ${
                                errors.selectedPlan
                                    ? "border-red-500"
                                    : "border-gray-300"
                            } ${plansLoading ? "opacity-50 cursor-not-allowed" : ""}`}
                        >
                            <option value="">
                                {plansLoading 
                                    ? "Loading plans..." 
                                    : plansError 
                                        ? "Error loading plans" 
                                        : plans.length === 0 
                                            ? "No plans available" 
                                            : "Select a plan"}
                            </option>
                            {plans.length > 0 ? (
                                [...plans]
                                    .sort((a: any, b: any) => (a.order || 0) - (b.order || 0))
                                    .map((plan: any) => {
                                        // Format the plan name better - show billing interval and price
                                        const amount = plan.cents ? `$${(plan.cents / 100).toFixed(2)}` : '';
                                        const interval = plan.interval ? `/${plan.interval}` : '';
                                        const displayName = plan.name || 'Corporate License';
                                        return (
                                        <option key={plan.priceId} value={plan.priceId}>
                                                {displayName} - {plan.keys} {plan.keys === 1 ? "license" : "licenses"} {amount && interval ? `(${amount}${interval})` : ''}
                                        </option>
                                        );
                                    })
                            ) : (
                                !plansLoading && !plansError && (
                                    <option value="" disabled>
                                        No corporate plans found
                                    </option>
                                )
                            )}
                        </select>
                        <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                            <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                            </svg>
                        </div>
                    </div>
                    {errors.selectedPlan && (
                        <p className="mt-1 text-sm text-red-500">{errors.selectedPlan}</p>
                    )}
                    {plansError && (
                        <p className="mt-1 text-sm text-yellow-600">
                            Warning: Could not load plans. {plansError.message || "Please check your connection and try again."}
                        </p>
                    )}
                    {!plansLoading && !plansError && plans.length === 0 && (
                        <p className="mt-1 text-sm text-yellow-600">
                            No corporate plans are currently available. Please contact support.
                        </p>
                    )}
                </div>

                {/* Coupon Code */}
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1.5">
                        Coupon Code (Optional)
                    </label>
                    <div className="flex gap-2">
                        <div className="relative flex-1">
                        <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                            <svg
                                className="h-5 w-5 text-gray-400"
                                fill="none"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth="2"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                            >
                                <path d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                            </svg>
                        </div>
                        <input
                            type="text"
                            value={couponCode}
                                onChange={(e) => {
                                    const newValue = e.target.value;
                                    setCouponCode(newValue);
                                    
                                    // If user deletes the auto-generated coupon, clear it
                                    if (newValue === "" && autoGeneratedCoupon) {
                                        handleClearCoupon();
                                        return;
                                    }
                                    
                                    // Reset validation when user types
                                    if (couponValid !== null) {
                                        setCouponValid(null);
                                        setCouponDiscount("");
                                        setCouponError("");
                                    }
                                    
                                    // Clear auto-generated flag if user modifies the code
                                    if (newValue !== autoGeneratedCoupon) {
                                        setAutoGeneratedCoupon("");
                                    }
                                }}
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter') {
                                        e.preventDefault();
                                        handleApplyCoupon();
                                    }
                                }}
                                className={`w-full pl-10 pr-10 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 ${
                                    couponValid === true
                                        ? "border-green-500 focus:ring-green-500"
                                        : couponValid === false
                                        ? "border-red-500 focus:ring-red-500"
                                        : "border-gray-300 focus:border-gray-700 focus:ring-gray-800"
                                }`}
                                placeholder="Enter coupon code"
                                disabled={isValidatingCoupon}
                            />
                            {couponCode && (
                                <button
                                    type="button"
                                    onClick={handleClearCoupon}
                                    className="absolute inset-y-0 right-0 pr-3 flex items-center text-gray-400 hover:text-gray-600 focus:outline-none"
                                    title="Clear coupon code"
                                >
                                    <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                    </svg>
                                </button>
                            )}
                    </div>
                        <button
                            type="button"
                            onClick={() => handleApplyCoupon()}
                            disabled={isValidatingCoupon || !couponCode.trim()}
                            className="px-4 py-2 bg-black text-white rounded-lg hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                            {isValidatingCoupon ? "Validating..." : "Apply"}
                        </button>
                    </div>
                    {couponValid === true && couponDiscount && (
                        <p className="mt-1.5 text-sm text-green-600 font-medium">
                            ✓ {couponDiscount} applied
                        </p>
                    )}
                    {couponValid === false && couponError && (
                        <p className="mt-1.5 text-sm text-red-500">
                            {couponError}
                        </p>
                    )}
                    {couponCode.trim() && couponValid === null && !isValidatingCoupon && (
                        <p className="mt-1.5 text-sm text-gray-500">
                            Click "Apply" to validate your coupon code
                        </p>
                    )}
                </div>

                {/* Company Address */}
                <div className="space-y-4">
                <div>
                        <div className="flex items-center justify-between mb-1.5">
                            <label className="block text-sm font-medium text-gray-700">
                                Company Address (Optional)
                            </label>
                        </div>
                        <div className="space-y-3">
                            {/* Address Line 1 */}
                            <div>
                                <label className="block text-xs font-medium text-gray-600 mb-1">
                                    Address Line 1
                    </label>
                    <input
                        type="text"
                                    value={addr1}
                                    onChange={(e) => setAddr1(e.target.value)}
                                    className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 ${
                                        errors.address ? "border-red-500 focus:ring-red-500" : "border-gray-300 focus:border-gray-700 focus:ring-gray-800"
                                    }`}
                                    placeholder="123 Main Street"
                    />
                </div>

                            {/* Address Line 2 */}
                            <div>
                                <label className="block text-xs font-medium text-gray-600 mb-1">
                                    Address Line 2 <span className="text-gray-400">(Optional)</span>
                    </label>
                    <input
                        type="text"
                                    value={addr2}
                                    onChange={(e) => setAddr2(e.target.value)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-gray-800 focus:border-gray-700"
                                    placeholder="Suite 100, Apt 4B, etc."
                    />
                </div>

                            {/* City, State, ZIP in a grid */}
                            <div className="grid grid-cols-3 gap-3">
                                <div className="col-span-2">
                                    <label className="block text-xs font-medium text-gray-600 mb-1">
                                        City
                                    </label>
                                    <input
                                        type="text"
                                        value={city}
                                        onChange={(e) => setCity(e.target.value)}
                                        className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 ${
                                            errors.address ? "border-red-500 focus:ring-red-500" : "border-gray-300 focus:border-gray-700 focus:ring-gray-800"
                                        }`}
                                        placeholder="City"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-medium text-gray-600 mb-1">
                                        State / Province
                                    </label>
                                    <div className="relative">
                    <input
                                            type="text"
                                            value={state ? getStateDisplay(state) : stateSearch}
                                            onChange={(e) => {
                                                const value = e.target.value;
                                                setStateSearch(value);
                                                setShowStateDropdown(true);
                                                
                                                // Clear state when user starts typing
                                                if (state) {
                                                    setState("");
                                                }
                                                
                                                // Try to match as user types
                                                if (value.length >= 2) {
                                                    // First try exact code match
                                                    let match = allStateOptions.find(
                                                        (s) => s.code.toLowerCase() === value.toLowerCase()
                                                    );
                                                    
                                                    // If no code match, try name match (allows typing "New York")
                                                    if (!match && value.length > 2) {
                                                        match = allStateOptions.find(
                                                            (s) => s.name.toLowerCase() === value.toLowerCase() ||
                                                                   s.name.toLowerCase().startsWith(value.toLowerCase()) ||
                                                                   value.toLowerCase().includes(s.name.toLowerCase())
                                                        );
                                                    }
                                                    
                                                    if (match) {
                                                        setState(match.code);
                                                        setStateSearch("");
                                                        setShowStateDropdown(false);
                                                    }
                                                }
                                            }}
                                            onFocus={() => {
                                                setShowStateDropdown(true);
                                                // If state is already set, allow editing by showing the name
                                                if (state) {
                                                    setStateSearch(getStateName(state));
                                                    setState("");
                                                }
                                            }}
                                            onBlur={() => {
                                                // Delay to allow click on dropdown item
                                                setTimeout(() => {
                                                    setShowStateDropdown(false);
                                                    // If stateSearch has a value but state is not set, try to match it
                                                    if (stateSearch && !state) {
                                                        // Try exact matches first (by name or code)
                                                        let match = allStateOptions.find(
                                                            (s) => s.name.toLowerCase() === stateSearch.toLowerCase() ||
                                                                   s.code.toLowerCase() === stateSearch.toLowerCase()
                                                        );
                                                        
                                                        // If no exact match, try partial match
                                                        if (!match) {
                                                            match = allStateOptions.find(
                                                                (s) => s.name.toLowerCase().includes(stateSearch.toLowerCase()) ||
                                                                       stateSearch.toLowerCase().includes(s.name.toLowerCase())
                                                            );
                                                        }
                                                        
                                                        if (match) {
                                                            setState(match.code);
                                                            setStateSearch("");
                                                        } else {
                                                            // Clear if no match found
                                                            setStateSearch("");
                                                        }
                                                    } else if (!stateSearch && state) {
                                                        // If search is cleared but state is set, keep the state
                                                        setStateSearch("");
                                                    }
                                                }, 200);
                                            }}
                                            className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 ${
                                                errors.address ? "border-red-500 focus:ring-red-500" : "border-gray-300 focus:border-gray-700 focus:ring-gray-800"
                                            }`}
                                            placeholder="Select State"
                                        />
                                        {showStateDropdown && filteredStates.length > 0 && (
                                            <div className="absolute z-[10000] w-full mt-1 bg-white border border-gray-300 rounded-lg shadow-lg max-h-60 overflow-auto">
                                                {filteredStates.map((option) => (
                                                    <button
                                                        key={option.code}
                                                        type="button"
                                                        onClick={() => {
                                                            setState(option.code);
                                                            setStateSearch("");
                                                            setShowStateDropdown(false);
                                                        }}
                                                        className="w-full text-left px-3 py-2 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none text-sm"
                                                    >
                                                        <div className="flex items-center justify-between">
                                                            <span>
                                                                {option.country === "United States" || option.country === "Canada"
                                                                    ? `${option.name} - ${option.code}`
                                                                    : option.name}
                        </span>
                                                            {option.country && option.country !== "United States" && (
                                                                <span className="text-xs text-gray-500 ml-2">{option.country}</span>
                                                            )}
                                                        </div>
                                                    </button>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* ZIP Code */}
                            <div>
                                <label className="block text-xs font-medium text-gray-600 mb-1">
                                    ZIP Code
                    </label>
                                <input
                                    type="text"
                                    value={zip}
                                    onChange={(e) => {
                                        const value = e.target.value.replace(/\D/g, '');
                                        if (value.length <= 10) {
                                            setZip(value);
                                        }
                                    }}
                                    className={`w-full px-3 py-2 border rounded-lg bg-white focus:outline-none focus:ring-2 ${
                                        errors.address ? "border-red-500 focus:ring-red-500" : "border-gray-300 focus:border-gray-700 focus:ring-gray-800"
                                    }`}
                                    placeholder="10001"
                                    maxLength={10}
                                />
                            </div>
                        </div>
                        {errors.address && (
                            <p className="mt-1.5 text-sm text-red-500">{errors.address}</p>
                        )}
                    </div>
                </div>

                {/* Submit Error */}
                {errors.submit && (
                    <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
                        <p className="text-sm text-red-600">{errors.submit}</p>
                    </div>
                )}

                {/* Action Buttons */}
                <div className="flex justify-end gap-3 pt-4">
                    <button
                        type="button"
                        onClick={handleClose}
                        disabled={isSubmitting}
                        className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 bg-white hover:bg-gray-50 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        Cancel
                    </button>
                    <button
                        type="submit"
                        disabled={isSubmitting}
                        className="px-3 py-2 text-sm text-white rounded-lg transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                        style={{ backgroundColor: "#064126" }}
                        onMouseEnter={(e) => {
                            if (!e.currentTarget.disabled) {
                                e.currentTarget.style.backgroundColor = "#052a1a";
                            }
                        }}
                        onMouseLeave={(e) => {
                            if (!e.currentTarget.disabled) {
                                e.currentTarget.style.backgroundColor = "#064126";
                            }
                        }}
                    >
                        {isSubmitting ? (
                            <>
                                <svg
                                    className="animate-spin h-4 w-4"
                                    xmlns="http://www.w3.org/2000/svg"
                                    fill="none"
                                    viewBox="0 0 24 24"
                                >
                                    <circle
                                        className="opacity-25"
                                        cx="12"
                                        cy="12"
                                        r="10"
                                        stroke="currentColor"
                                        strokeWidth="4"
                                    ></circle>
                                    <path
                                        className="opacity-75"
                                        fill="currentColor"
                                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                                    ></path>
                                </svg>
                                Processing...
                            </>
                        ) : (
                            "Review Information"
                        )}
                    </button>
                </div>
            </form>
            )}
        </Modal>
    );
}

